# Generated by Django 4.2.4 on 2024-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('duration', models.DurationField()),
                ('scores', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
