# Generated by Django 4.2.4 on 2024-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scores',
            field=models.JSONField(default={}),
        ),
    ]
